line-length = 88

# removes warning for some of the rule sets
preview = true
lint.select = ["E", "F", "B", "S"]
lint.ignore = [
    # allow extra whitespace
    "E203",
    # allow long lines
    "E501",
    # allow multiple '#' chars for comment "headings" of different
    # levels
    "E266",
]

[lint.per-file-ignores]

"tests/*" = [
    # allow assert
    "S101",
    # allow `assert False` for missing tests
    "B011",
    # ignore "pythonic" comparisons to booleans, for clarity in
    # writing tests e.g. `assert thing is False`
    "E712",
    # its okay to have subprocess in tests
    "S603",
    "S404",
    # don't be strict about unused assigned variables
    "F841",
]
